# Generated by Django 4.1.4 on 2023-01-29 18:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 29, 18, 0, 57, 974854)),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 29, 18, 0, 57, 974247)),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
