# Generated by Django 4.1.4 on 2023-01-31 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_review_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="genres",
        ),
        migrations.AddField(
            model_name="book",
            name="genres",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.genre"
            ),
            preserve_default=False,
        ),
    ]
