# Generated by Django 4.1.4 on 2023-01-28 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comment_time_alter_reply_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fav_blooks',
        ),
        migrations.AddField(
            model_name='user',
            name='fav_books',
            field=models.ManyToManyField(blank=True, db_table='app_user_fav_books', to='core.book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 28, 18, 50, 42, 709117)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 28, 18, 50, 42, 709756)),
        ),
    ]
