# Generated by Django 4.1.4 on 2023-01-28 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_fav_blooks_user_fav_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 28, 22, 59, 12, 314054)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.TimeField(auto_now=datetime.datetime(2023, 1, 28, 22, 59, 12, 314855)),
        ),
    ]
