# Generated by Django 4.1.1 on 2022-12-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="publishers",
        ),
    ]
