# Generated by Django 4.1.1 on 2022-12-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_author_publishers"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="publishers",
            field=models.ManyToManyField(to="core.publisher"),
        ),
    ]
