# Generated by Django 4.1.1 on 2023-01-02 20:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genre_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default.jpg', upload_to=core.models.upload_location_books),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/default.jpg', null=True, upload_to=core.models.upload_location_users),
        ),
    ]
