# Generated by Django 4.1.4 on 2022-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_author_publishers"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(default="images/default.jpg", upload_to="images/"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favourites",
            field=models.ManyToManyField(
                blank=True, related_name="favourite_books", to="core.book"
            ),
        ),
    ]
