# Generated by Django 4.1.4 on 2022-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_book_image_customuser_favourites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="images/"),
        ),
    ]
