# Generated by Django 4.1.1 on 2023-01-03 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_book_image_alter_customuser_image'),
        ('core', '0005_alter_rating_unique_together_alter_book_avg_rating_and_more'),
    ]

    operations = [
    ]
