# Generated by Django 4.1.4 on 2023-01-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rating_unique_together_alter_book_avg_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
