# Generated by Django 4.1.4 on 2023-01-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20230103_0406"),
        ("core", "0007_alter_book_genres"),
    ]

    operations = []
