# Generated by Django 4.1.4 on 2023-01-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_0006_merge_20230103_0406_0007_alter_book_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='core.genre'),
        ),
    ]
